### ISSUE TITLE
GitHub Classroom

### ISSUE THREAD

**Issue by vickjoeobi** [ReDI-School/nrw-html-and-css-2021-spring#35]
Dear @ReDI-School/nrw-html-and-css , 

As discussed in the last meeting, I think we should consider starting the test of `GitHub Classrooms`. This will help us in quickly deploying it to the students when the time comes. 

Thanks.

**Comment by impactmass** [comment]
Hey @vickjoeobi, this is a good idea. Angel wrote it down when you suggested it. It is in the "Improvement Ideas" list here https://github.com/ReDI-School/nrw-html-and-css-2021-spring/blob/bc0bbae9416e9ad7524685418e900e5ba66bf734/teacher/ImprovementIdeas.md#idea-1

I think the next question is "when to test it out". At the moment, it is listed as an idea for next semester. What do you think?

**Comment by vickjoeobi** [comment]
I think we should add this also as a subject of next meeting. 

We would then conclude on the best time for that.
